# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-UploadMirror
version:      0.04
version_from: lib/Net/UploadMirror.pm
installdirs:  site
requires:
    File::Basename:                
    Net::MirrorDir:                Storable

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
